export const FETCH_PRODUCTS ='FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_QTY_OF_PRODUCT_IN_CART = 'INCREASE_QTY_OF_PRODUCT_IN_CART';
export const DECREASE_QTY_OF_PRODUCT_IN_CART = 'DECREASE_QTY_OF_PRODUCT_IN_CART';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';